services:
  # MongoDB Service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Backend Service
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/medi-ghor
      - JWT_SECRET=abc123

  # Frontend Service
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000

volumes:
  mongo_data: