export const BRAND_LIST_REQUEST = 'BRAND_LIST_REQUEST';
export const BRAND_LIST_SUCCESS = 'BRAND_LIST_SUCCESS';
export const BRAND_LIST_FAIL = 'BRAND_LIST_FAIL';

export const FEATURED_BRANDS_REQUEST = 'FEATURED_BRANDS_REQUEST';
export const FEATURED_BRANDS_SUCCESS = 'FEATURED_BRANDS_SUCCESS';
export const FEATURED_BRANDS_FAIL = 'FEATURED_BRANDS_FAIL';
