export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';

export const FEATURED_CATEGORIES_REQUEST = 'FEATURED_CATEGORIES_REQUEST';
export const FEATURED_CATEGORIES_SUCCESS = 'FEATURED_CATEGORIES_SUCCESS';
export const FEATURED_CATEGORIES_FAIL = 'FEATURED_CATEGORIES_FAIL';
