export const CHAT_CREATE_REQUEST = 'CHAT_CREATE_REQUEST';
export const CHAT_CREATE_SUCCESS = 'CHAT_CREATE_SUCCESS';
export const CHAT_CREATE_FAIL = 'CHAT_CREATE_FAIL';

export const CHAT_LIST_REQUEST = 'CHAT_LIST_REQUEST';
export const CHAT_LIST_SUCCESS = 'CHAT_LIST_SUCCESS';
export const CHAT_LIST_FAIL = 'CHAT_LIST_FAIL';

export const CHAT_DETAILS_REQUEST = 'CHAT_DETAILS_REQUEST';
export const CHAT_DETAILS_SUCCESS = 'CHAT_DETAILS_SUCCESS';
export const CHAT_DETAILS_FAIL = 'CHAT_DETAILS_FAIL';

export const CHAT_MESSAGE_ADD_REQUEST = 'CHAT_MESSAGE_ADD_REQUEST';
export const CHAT_MESSAGE_ADD_SUCCESS = 'CHAT_MESSAGE_ADD_SUCCESS';
export const CHAT_MESSAGE_ADD_FAIL = 'CHAT_MESSAGE_ADD_FAIL';

export const CHAT_IMAGE_ANALYZE_REQUEST = 'CHAT_IMAGE_ANALYZE_REQUEST';
export const CHAT_IMAGE_ANALYZE_SUCCESS = 'CHAT_IMAGE_ANALYZE_SUCCESS';
export const CHAT_IMAGE_ANALYZE_FAIL = 'CHAT_IMAGE_ANALYZE_FAIL';
