export const HEALTH_CONDITION_LIST_REQUEST = 'HEALTH_CONDITION_LIST_REQUEST';
export const HEALTH_CONDITION_LIST_SUCCESS = 'HEALTH_CONDITION_LIST_SUCCESS';
export const HEALTH_CONDITION_LIST_FAIL = 'HEALTH_CONDITION_LIST_FAIL';
