// Prescription List
export const PRESCRIPTION_LIST_REQUEST = 'PRESCRIPTION_LIST_REQUEST';
export const PRESCRIPTION_LIST_SUCCESS = 'PRESCRIPTION_LIST_SUCCESS';
export const PRESCRIPTION_LIST_FAIL = 'PRESCRIPTION_LIST_FAIL';
export const PRESCRIPTION_LIST_RESET = 'PRESCRIPTION_LIST_RESET';

// Prescription Details
export const PRESCRIPTION_DETAILS_REQUEST = 'PRESCRIPTION_DETAILS_REQUEST';
export const PRESCRIPTION_DETAILS_SUCCESS = 'PRESCRIPTION_DETAILS_SUCCESS';
export const PRESCRIPTION_DETAILS_FAIL = 'PRESCRIPTION_DETAILS_FAIL';
export const PRESCRIPTION_DETAILS_RESET = 'PRESCRIPTION_DETAILS_RESET';

// Prescription Create
export const PRESCRIPTION_CREATE_REQUEST = 'PRESCRIPTION_CREATE_REQUEST';
export const PRESCRIPTION_CREATE_SUCCESS = 'PRESCRIPTION_CREATE_SUCCESS';
export const PRESCRIPTION_CREATE_FAIL = 'PRESCRIPTION_CREATE_FAIL';
export const PRESCRIPTION_CREATE_RESET = 'PRESCRIPTION_CREATE_RESET';

// Prescription Update
export const PRESCRIPTION_UPDATE_REQUEST = 'PRESCRIPTION_UPDATE_REQUEST';
export const PRESCRIPTION_UPDATE_SUCCESS = 'PRESCRIPTION_UPDATE_SUCCESS';
export const PRESCRIPTION_UPDATE_FAIL = 'PRESCRIPTION_UPDATE_FAIL';
export const PRESCRIPTION_UPDATE_RESET = 'PRESCRIPTION_UPDATE_RESET';

// Prescription Delete
export const PRESCRIPTION_DELETE_REQUEST = 'PRESCRIPTION_DELETE_REQUEST';
export const PRESCRIPTION_DELETE_SUCCESS = 'PRESCRIPTION_DELETE_SUCCESS';
export const PRESCRIPTION_DELETE_FAIL = 'PRESCRIPTION_DELETE_FAIL';

// Prescription Upload
export const PRESCRIPTION_UPLOAD_REQUEST = 'PRESCRIPTION_UPLOAD_REQUEST';
export const PRESCRIPTION_UPLOAD_SUCCESS = 'PRESCRIPTION_UPLOAD_SUCCESS';
export const PRESCRIPTION_UPLOAD_FAIL = 'PRESCRIPTION_UPLOAD_FAIL';
export const PRESCRIPTION_UPLOAD_RESET = 'PRESCRIPTION_UPLOAD_RESET';
