export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';
export const USER_LIST_RESET = 'USER_LIST_RESET';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

// Firebase Authentication Constants
export const USER_FIREBASE_LOGIN_REQUEST = 'USER_FIREBASE_LOGIN_REQUEST';
export const USER_FIREBASE_LOGIN_SUCCESS = 'USER_FIREBASE_LOGIN_SUCCESS';
export const USER_FIREBASE_LOGIN_FAIL = 'USER_FIREBASE_LOGIN_FAIL';

export const USER_FIREBASE_REGISTER_REQUEST = 'USER_FIREBASE_REGISTER_REQUEST';
export const USER_FIREBASE_REGISTER_SUCCESS = 'USER_FIREBASE_REGISTER_SUCCESS';
export const USER_FIREBASE_REGISTER_FAIL = 'USER_FIREBASE_REGISTER_FAIL';

export const USER_GOOGLE_LOGIN_REQUEST = 'USER_GOOGLE_LOGIN_REQUEST';
export const USER_GOOGLE_LOGIN_SUCCESS = 'USER_GOOGLE_LOGIN_SUCCESS';
export const USER_GOOGLE_LOGIN_FAIL = 'USER_GOOGLE_LOGIN_FAIL';

// Saved Addresses Constants
export const USER_ADDRESSES_REQUEST = 'USER_ADDRESSES_REQUEST';
export const USER_ADDRESSES_SUCCESS = 'USER_ADDRESSES_SUCCESS';
export const USER_ADDRESSES_FAIL = 'USER_ADDRESSES_FAIL';
export const USER_ADDRESSES_RESET = 'USER_ADDRESSES_RESET';

export const USER_ADDRESS_ADD_REQUEST = 'USER_ADDRESS_ADD_REQUEST';
export const USER_ADDRESS_ADD_SUCCESS = 'USER_ADDRESS_ADD_SUCCESS';
export const USER_ADDRESS_ADD_FAIL = 'USER_ADDRESS_ADD_FAIL';
export const USER_ADDRESS_ADD_RESET = 'USER_ADDRESS_ADD_RESET';

export const USER_ADDRESS_UPDATE_REQUEST = 'USER_ADDRESS_UPDATE_REQUEST';
export const USER_ADDRESS_UPDATE_SUCCESS = 'USER_ADDRESS_UPDATE_SUCCESS';
export const USER_ADDRESS_UPDATE_FAIL = 'USER_ADDRESS_UPDATE_FAIL';
export const USER_ADDRESS_UPDATE_RESET = 'USER_ADDRESS_UPDATE_RESET';

export const USER_ADDRESS_DELETE_REQUEST = 'USER_ADDRESS_DELETE_REQUEST';
export const USER_ADDRESS_DELETE_SUCCESS = 'USER_ADDRESS_DELETE_SUCCESS';
export const USER_ADDRESS_DELETE_FAIL = 'USER_ADDRESS_DELETE_FAIL';
